Repository viniciusciunek/controle-rural-web3, pull requests merged in 2025-02, with the labels that each got.

#2 @viniciusciunek/1/feature/crud produtos
  .github/pull_request_template.md
  .vscode/tasks.json
  README.md
  package-lock.json
  package.json
  server/db.json
  src/app/app.component.html
  src/app/app.component.ts
  src/app/app.routes.ts
  src/app/components/error-button/error-button.component.css
  src/app/components/error-button/error-button.component.html
  src/app/components/error-button/error-button.component.spec.ts
  src/app/components/error-button/error-button.component.ts
  src/app/components/success-button/success-button.component.css
  src/app/components/success-button/success-button.component.html
  src/app/components/success-button/success-button.component.spec.ts
  src/app/components/success-button/success-button.component.ts
  src/app/navbar/navbar.component.css
  src/app/navbar/navbar.component.html
  src/app/navbar/navbar.component.spec.ts
  src/app/navbar/navbar.component.ts
  src/app/pages/produtos/deletar-produto/deletar-produto.component.css
  src/app/pages/produtos/deletar-produto/deletar-produto.component.html
  src/app/pages/produtos/deletar-produto/deletar-produto.component.spec.ts
  src/app/pages/produtos/deletar-produto/deletar-produto.component.ts
  src/app/pages/produtos/editar-produto/editar-produto.component.css
  src/app/pages/produtos/editar-produto/editar-produto.component.html
  src/app/pages/produtos/editar-produto/editar-produto.component.spec.ts
  src/app/pages/produtos/editar-produto/editar-produto.component.ts
  src/app/pages/produtos/index-produto/produtos.component.css
  src/app/pages/produtos/index-produto/produtos.component.html
  src/app/pages/produtos/index-produto/produtos.component.spec.ts
  src/app/pages/produtos/index-produto/produtos.component.ts
  src/app/pages/produtos/novo-produto/novo-produto.component.css
  src/app/pages/produtos/novo-produto/novo-produto.component.html
  src/app/pages/produtos/novo-produto/novo-produto.component.spec.ts
  src/app/pages/produtos/novo-produto/novo-produto.component.ts
  src/app/pages/produtos/produtos.component.html
  src/app/pages/produtos/produtos.component.ts
  src/app/pages/produtos/visualizar-produto/visualizar-produto.component.css
  src/app/pages/produtos/visualizar-produto/visualizar-produto.component.html
  src/app/pages/produtos/visualizar-produto/visualizar-produto.component.spec.ts
  src/app/pages/produtos/visualizar-produto/visualizar-produto.component.ts
  src/app/services/produtos.service.ts
Labels: enhancement

#5 finalizado despesas!
  server/db.json
  src/app/app.routes.ts
  src/app/navbar/navbar.component.html
  src/app/pages/despesas/index-despesa/index-despesa.component.css
  src/app/pages/despesas/index-despesa/index-despesa.component.html
  src/app/pages/despesas/index-despesa/index-despesa.component.spec.ts
  src/app/pages/despesas/index-despesa/index-despesa.component.ts
  src/app/pages/despesas/nova-despesa/nova-despesa.component.css
  src/app/pages/despesas/nova-despesa/nova-despesa.component.html
  src/app/pages/despesas/nova-despesa/nova-despesa.component.spec.ts
  src/app/pages/despesas/nova-despesa/nova-despesa.component.ts
  src/app/pages/despesas/visualizar-despesa/visualizar-despesa.component.css
  src/app/pages/despesas/visualizar-despesa/visualizar-despesa.component.html
  src/app/pages/despesas/visualizar-despesa/visualizar-despesa.component.spec.ts
  src/app/pages/despesas/visualizar-despesa/visualizar-despesa.component.ts
  src/app/pages/produtos/editar-produto/editar-produto.component.ts
  src/app/pages/produtos/index-produto/produtos.component.ts
  src/app/pages/produtos/novo-produto/novo-produto.component.ts
  src/app/pages/produtos/visualizar-produto/visualizar-produto.component.ts
  src/app/services/categorias.service.spec.ts
  src/app/services/categorias.service.ts
  src/app/services/despesas-produtos.service.spec.ts
  src/app/services/despesas-produtos.service.ts
  src/app/services/despesas.service.spec.ts
  src/app/services/despesas.service.ts
  src/app/services/produtos.service.ts
Labels: enhancement

#7 @mauriciostempinhaki/fix/merge fixes
  server/db.json
  src/app/app.routes.ts
Labels: bug

#8 @viniciusciunek/fix/update readme
  README.md
  server/db.json
  src/app/app.routes.ts
Labels: documentation

#10 feature: criado pagina de relatorios
  server/db.json
  src/app/app.routes.ts
  src/app/navbar/navbar.component.html
  src/app/pages/relatorios/index-relatorio/index-relatorio.component.css
  src/app/pages/relatorios/index-relatorio/index-relatorio.component.html
  src/app/pages/relatorios/index-relatorio/index-relatorio.component.spec.ts
  src/app/pages/relatorios/index-relatorio/index-relatorio.component.ts
Labels: enhancement

#12 @viniciusciunek/11/feature/guard routes
  server/db.json
  src/app/app.component.html
  src/app/app.component.ts
  src/app/app.routes.ts
  src/app/guards/auth.guard.ts
  src/app/navbar/navbar.component.html
  src/app/navbar/navbar.component.ts
  src/app/pages/dashboard/dashboard.component.css
  src/app/pages/dashboard/dashboard.component.html
  src/app/pages/dashboard/dashboard.component.spec.ts
  src/app/pages/dashboard/dashboard.component.ts
  src/app/pages/login/login.component.html
  src/app/pages/login/login.component.ts
  src/app/services/auth.service.ts
Labels: enhancement

#13 update readme
  README.md
  server/db.json
Labels: documentation
